title: Deployment Hardware Adapter (DHA)
# DHA API version supported
version: 1.1
created: Mon May  4 09:03:46 UTC 2015
comment: Test environment Ericsson Montreal

# Adapter to use for this definition
adapter: ipmi

# Node list.
# Mandatory properties are id and role.
# The MAC address of the PXE boot interface for Fuel is not
# mandatory to be defined.
# All other properties are adapter specific.

nodes:
- id: 1
  pxeMac: 14:58:D0:54:7A:28
  ipmiIp: 10.118.32.205
  ipmiUser: username
  ipmiPass: password
- id: 2
  pxeMac: 14:58:D0:55:E2:E0
  ipmiIp: 10.118.32.202
  ipmiUser: username
  ipmiPass: password
# Adding the Fuel node as node id 3 which may not be correct - please
# adjust as needed.
- id: 3
  libvirtName: vFuel
  libvirtTemplate: vFuel
  isFuel: yes
  username: root
  password: r00tme

# Deployment power on strategy
# all:      Turn on all nodes at once. There will be no correlation
#           between the DHA and DEA node numbering. MAC addresses
#           will be used to select the node roles though.
# sequence: Turn on the nodes in sequence starting with the lowest order
#           node and wait for the node to be detected by Fuel. Not until
#           the node has been detected and assigned a role will the next
#           node be turned on.
powerOnStrategy: sequence

# If fuelCustomInstall is set to true, Fuel is assumed to be installed by
# calling the DHA adapter function "dha_fuelCustomInstall()"  with two
# arguments: node ID and the ISO file name to deploy. The custom install
# function is then to handle all necessary logic to boot the Fuel master
# from the ISO and then return.
# Allowed values: true, false
fuelCustomInstall: true

