title: Deployment Hardware Adapter (DHA)
# DHA API version supported
version:
created:
comment: Config for LF POD2

# Adapter to use for this definition
adapter: ipmi

# Node list.
# Mandatory property is id, all other properties are adapter specific.

nodes:
- id: 1
  pxeMac: 00:25:b5:a0:00:2b
  ipmiIp: 172.30.8.75
  ipmiUser: admin
  ipmiPass: octopus
- id: 2
  pxeMac: 00:25:b5:a0:00:3b
  ipmiIp: 172.30.8.65
  ipmiUser: admin
  ipmiPass: octopus
- id: 3
  pxeMac: 00:25:b5:a0:00:4b
  ipmiIp: 172.30.8.74
  ipmiUser: admin
  ipmiPass: octopus
- id: 4
  pxeMac: 00:25:b5:a0:00:5b
  ipmiIp: 172.30.8.73
  ipmiUser: admin
  ipmiPass: octopus
- id: 5
  pxeMac: 00:25:b5:a0:00:6b
  ipmiIp: 172.30.8.72
  ipmiUser: admin
  ipmiPass: octopus
# Adding the Fuel node as node id 6 which may not be correct - please
# adjust as needed.
- id: 6
  libvirtName: fuel-opnfv
  libvirtTemplate: baremetal/vms/fuel_lf.xml
  isFuel: yes
  username: root
  password: r00tme

disks:
  fuel: 30G
